### ISSUE TITLE
Error in com.github.sheagcraig.munki.Eclipse: No match found on https://eclipse.org/downloads/

### ISSUE THREAD

**Issue by pereiraa-wellesleyps** [autopkg/sheagcraig-recipes#17]
This is a great recipe, which was working until fairly recently (maybe the last couple weeks?), but now fails with:
> Error in com.github.sheagcraig.munki.Eclipse: Processor: URLTextSearcher: Error: No match found on URL: https://eclipse.org/downloads/

**Comment by sheagcraig** [comment]
There you go @pereiraa-wellesleyps.

Eclipse both moved the downloads page, and changed their download URL scheme very slightly. I updated the regexes for each of the projects listed in the recipe.
