### ISSUE TITLE
SketchUp.munki doesn't install all packages

### ISSUE THREAD

**Issue by erikng** [autopkg/sheagcraig-recipes#21]
I'm not sure if this is intentional, but I've been writing a munki recipe for another piece of software and tried to find examples of how to do it and this DMG is the closest/problematic one.

I've now figured out how to do it without repackaging and it can support multiple applications from a single DMG. While I don't use Sketchup, I figured this could help you if you decide to want to fix it or add an alternative SketchUp.munki.recipe

https://github.com/erikng/erikng-recipes/blob/master/Genymobile/Genymotion.munki.recipe

:edit:

You wouldn't need to do the hashes or even the copies.

**Comment by sheagcraig** [comment]
That's cool-thanks!

I wonder if there's a way to make this all run off of input variables too. Something I'll have to think about. I'm sure it's probably easier to just individually provide parts then to try to parameterize the recipe, but it's an interesting idea.

I'll definitely have to add this to the SketchUp recipe.

**Comment by erikng** [comment]
If we could make it more dynamic I would definitely be interested. This was the best I could do for now but I'm not that happy with it. The code signature validation requires multiple mounts/unmounts as well as the file copier. It's a sluggish recipe but at least it doesn't require repackaging.

**Comment by homebysix** [comment]
This repository is deprecated and will soon be archived (#71). It looks like there are a few alternative SketchUp recipes out there, and any improvements should be submitted as PRs to one of those. Thanks!
