### ISSUE TITLE
[Eclipse.download] No match found for default selection

### ISSUE THREAD

**Issue by andrewvalentine** [autopkg/sheagcraig-recipes#30]
Hi there,

When running an override of Eclipse.munki.recipe, I see the following:

```
'selection': u'Eclipse IDE for Java Developers'}}
OptionSelector: No value supplied for result_output_var_name, setting default value of: selection
OptionSelector: Selection 'Eclipse IDE for Java Developers': 'href="\/downloads\/download\.php\?file=([/\w]+eclipse-java[\w-]+macosx-cocoa-x86_64\.tar\.gz)"'
{'Output': {'selection': u'href="\\/downloads\\/download\\.php\\?file=([/\\w]+eclipse-java[\\w-]+macosx-cocoa-x86_64\\.tar\\.gz)"'}}
URLTextSearcher
{'Input': {'re_pattern': u'href="\\/downloads\\/download\\.php\\?file=([/\\w]+eclipse-java[\\w-]+macosx-cocoa-x86_64\\.tar\\.gz)"',
           'request_headers': {
    "user-agent" = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.39 (KHTML, like Gecko) Version/9.0 Safari/601.1.39";
},
           'result_output_var_name': u'match',
           'url': u'https://eclipse.org/downloads/eclipse-packages/'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
No match found on URL: https://eclipse.org/downloads/eclipse-packages/
```

The filename that the selection needs to search for now appears to be:

```
 eclipse-jee-oxygen-R-macosx-cocoa-x86_64.dmg
```

I'm afraid I'm not good enough at regex to submit a PR for this. Sorry!

**Comment by krispayne** [comment]
Seems they've just changed where the php downloader looks for the file:
`https://eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/R/eclipse-cpp-oxygen-R-macosx-cocoa-x86_64.dmg`
as opposed to:
`https://eclipse.org/downloads/download\.php\?file=([/\w]+eclipse-jee[\w-]+macosx-cocoa-x86_64\.tar\.gz`

Looks like all of them are now under this newer release style path

**Comment by krispayne** [comment]
also, I think more than just the filename's will need to change. It's going to tar.gz to .dmg, so a different processor will be needed.

**Comment by macmule** [comment]
Looks like that might be addressed in: https://github.com/autopkg/sheagcraig-recipes/pull/29

**Comment by TomWebster** [comment]
Hi there,

 I think that the download URL's have changed since this repo was last updated.

**Comment by homebysix** [comment]
The sheagcraig-recipes repo is [being deprecated](https://github.com/autopkg/sheagcraig-recipes/issues/71), but the Eclipse.download recipe has been [moved to homebysix-recipes](https://github.com/autopkg/homebysix-recipes/blob/master/Eclipse/Eclipse.download.recipe). I believe this issue has been fixed.
