### ISSUE TITLE
SketchUpMake.pkg.recipe  broken

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/sheagcraig-recipes#4]
SketchUpMake.pkg.recipe  is broken.

    Path '/private/tmp/dmg.zmq1eF/SketchUp 2014/SketchUp.app' doesn't exist!
    Failed.

 SketchUP dmg now contains "SketchUp 2015" folder.

**Comment by sheagcraig** [comment]
@MichalMMac Are you sure you have the newest version? (i.e. ```autopkg repo-update sheagcraig-recipes```

**Comment by MichalMMac** [comment]
Whops.Sorry. I run into some problem with AutoPKGr munki recipe. Than tested in on another  Mac with autopkg  where I of course forgot to update recipes :-/
