### ISSUE TITLE
Geogebra download failing

### ISSUE THREAD

**Issue by everetteallen** [autopkg/sheagcraig-recipes#41]
Shea,
The Geogebra download recipe but it is giving:
Can't download http://www.geogebra.org/download/?os=mac: <urlopen error [Errno 1] _ssl.c:507: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

**Comment by AllWorkAndNoPlay** [comment]
@everetteallen If you look at https://www.geogebra.org/download ; GeoGebra is not offering a download link. All the links now point to the Apple App Store. Looks like it's time to use VPP if you want to distribute the app. 

FYI
GeoGebra Graphing Calculator, Geometry, 3D Graphics Calculator, Classic are now all web apps.

**Comment by homebysix** [comment]
The sheagcraig-recipes repo is deprecated (details at https://github.com/autopkg/sheagcraig-recipes/issues/71). There are other Geogebra recipes available in other repos, but given @AllWorkAndNoPlay's comment above it could be that they are all broken now.
