### ISSUE TITLE
Skitch recipe failing with a ditto error

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/sheagcraig-recipes#53]
Getting the below error when running the Skitch download recipe:

`Processor: Unarchiver: Error: Unarchiving /Users/sadmin/Library/AutoPkg/Cache/local.munki.Skitch-dataJAR/downloads/Skitch.zip with ditto failed: ditto: Couldn't read PKZip signature `

I'm struggling to find anything official but:
1) The download link for Skitch redirects to the main Evernote download
2) Cult of Mac article about dropping Skitch https://www.cultofmac.com/402612/evernote-is-killing-skitch-clearly-and-its-pebble-app/
3) The App is still available in the Mac App Store.

Not sure if the common consensus here is that the our of MAS download is no longer a thing.

**Comment by Daz-wallace** [comment]
Hi Folks,

Any further thoughts or opinions here?

Thanks!

**Comment by apizz** [comment]
Getting the same.  Seems like App Store is only option now.  In that case, I'd probably setup with VPP & use nmcspadden's AppStoreApp recipes
