### ISSUE TITLE
AdobeDNGConverter.download.recipe no longer work

### ISSUE THREAD

**Issue by adrienlabigne** [autopkg/sheagcraig-recipes#65]
Hi !

It seems Adobe change there patern for download link, so on my Autopkg, this recipe doesn't work anymore.
Is it same for you ?

Thanks !

**Comment by dcoobs** [comment]
Looks like changing the following line to HTTPS should fix it
https://github.com/autopkg/sheagcraig-recipes/blob/0b5ed61797a88e8eba8fd3ca78f3fef3cea4a391/AdobeDNGCoverter/AdobeDNGConverter.download.recipe#L40

**Comment by dcoobs** [comment]
Looks like Adobe DNG Converter is behind an Adobe sign-in page now

**Comment by TekTekkers** [comment]
Im getting the same issue.
Changed the URL still nothing.

**Comment by dcoobs** [comment]
It looks like now the DMG is available directly at https://www.adobe.com/go/dng_converter_mac

**Comment by homebysix** [comment]
@dcoobs Thank you for that! I'm making new recipes now, which I'll host in homebysix-recipes.
