### ISSUE TITLE
AirServer Download warning

### ISSUE THREAD

**Issue by eshirk** [autopkg/sheagcraig-recipes#66]
Seeing the following warning during code signature verification:

CodeSignatureVerifier: WARNING: This recipe is using 'requirements' when it should be using 'requirement'. This will become an error in future versions of AutoPkg.

**Comment by homebysix** [comment]
The fix is included in https://github.com/autopkg/sheagcraig-recipes/pull/62.

**Comment by eshirk** [comment]
Thanks, and will close this issue.
