### ISSUE TITLE
eclipse binary permissions unable to launch app as standard user

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/sheagcraig-recipes#7]
/Applications/eclipse/Eclipse.app/Contents/MacOS/eclipse has 750 permissions with root:admin ownerwhip.

Standard users are unable to launch Eclipse.app directly.

Is this somehow by design?

**Comment by sheagcraig** [comment]
No, that sounds like a mistake to me.

Strangely enough that happens on its own. There's nothing in the recipe setting it as such. I'll take a look at that this morning.

**Comment by sheagcraig** [comment]
...but it seems like an upstream mistake. Take a look (at least at the first message) here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=442607

We can certainly override that in the pkg recipe if needed. And depending on your method of deploying this package, a followup-action of some kind to `chmod 755 /Applications/eclipse/Eclipse.app/Contents/MacOS/eclipse` would work to.

What do you think: Should the autopkg recipe leave the product as-supplied-by-the-vendor? Or should it try to smooth over their mistakes?

**Comment by MichalMMac** [comment]
I fixed it by postinstall script in munki.

 That bugreport is one year old. I hope it is fixed in next Eclipse relase (4.5) which is due soon. I'll take a look.

Well you are crating new package. Why not set correct permissions. It may save someone else's time when he ecounters this problem.
Your call.

**Comment by MichalMMac** [comment]
Unfortunately it is not fixed in 4.5 RC4. Eclipse binary still has 750 permissions :-(

**Comment by sheagcraig** [comment]
Yeah-the discussion on the list is old, and they don't seem to really know how to solve it!

I think I'll just update it in the pkg recipe. Look for it soon!

**Comment by sheagcraig** [comment]
Fixed!
