### ISSUE TITLE
Version differences in recipe vs JSS

### ISSUE THREAD

**Issue by JonMunford** [autopkg/sheagcraig-recipes#8]
Hey Shea,

I have a few recipes that have smart update groups that are looking for versions such as 7.10.0.776 however the JSS is only reporting the application on the computer to 7.10, so even if the application is updated completely the computer will always be part of the smart group and therefor the policy will run even if it's updated.  Is there a fix for this or a way to get the JSS to report more detailed versions?  This is happening on Skype, Google Drive, and Google Earth.

**Comment by sheagcraig** [comment]
Hey Jon-
Take a look at https://github.com/autopkg/jss-recipes where we moved the "official" jss-recipes repo.

Skype, Google Earth, etc, use a common Extension Attribute and Smart Group template for properly determining version (CFBundleVersionExtensionAttribute.xml, CFBundleVersionSmartGroupTemplate.xml).

There's no way that I know of to get the JSS to use the more detailed version number. Hopefully they'll add that feature in the future. Until then, we need to use an extension attribute.

**Comment by JonMunford** [comment]
Thats exactly what I needed.  Thanks again Shea.

**Comment by sheagcraig** [comment]
No problem.
